# Generated by Django 4.0.1 on 2022-08-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_product_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='restaurant_id',
            field=models.IntegerField(),
        ),
    ]
